---
- name: Add TDengine apt repository key
  apt_key:
    url: https://repos.taosdata.com/TDengine-release/TDengine-GPG-KEY-public
    state: present
  become: yes

- name: Add TDengine apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://repos.taosdata.com/TDengine-release/ stable main"
    state: present
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install tdengine package
  apt:
    name: tdengine
    state: present
  become: yes

- name: Configure tdengine
  template:
    src: tdengine.conf.j2
    dest: /etc/tdengine/tdengine.conf
  notify: restart tdengine
  become: yes

- name: Ensure tdengine service is started
  service:
    name: tdengine
    state: started
    enabled: yes
  become: yes
